export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL'

export const REMOVE_ITEM_TO_CART = 'REMOVE_ITEM_TO_CART'
export const REMOVE_ITEM_TO_CART_FAIL = 'REMOVE_ITEM_TO_CART_FAIL'