export const GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST'
export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL'

export const GET_REGISTER = 'GET_REGISTER'
export const GET_REGISTER_FAIL = 'GET_REGISTER_FAIL'