export const LOGIN_EMAIL = 'LOGIN_EMAIL'
export const LOGIN_EMAIL_FAIL = 'LOGIN_EMAIL_FAIL'

export const LOGIN_PASSWORD = 'LOGIN_PASSWORD'
export const LOGIN_PASSWORD_FAIL = 'LOGIN_PASSWORD_FAIL'

export const LOGIN_DATA_REQUEST = 'LOGIN_DATA_REQUEST'
export const LOGIN_DATA = 'LOGIN_DATA'
export const LOGIN_DATA_FAIL = 'LOGIN_DATA_FAIL'
